### ISSUE TITLE
Mine keeps giving me "ghost zips"

### ISSUE THREAD

**Issue by 53545** [Guergeiro/twitch-emotes-downloader#4]
Runnin it on pydroid3 and it loads zip files as intended but its always empty with no emotes at all

**Comment by Guergeiro** [comment]
Hello @53545, I cannot reproduce this issue. Can you tell me your steps so that I can reproduce this issue?

**Comment by Guergeiro** [comment]
Closed due inactivity. Feel free to reopen if the issue persists.
